# Generated by Django 3.2.20 on 2023-08-26 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('author_id', models.CharField(max_length=50)),
                ('author_img', models.CharField(blank=True, max_length=100)),
                ('fans', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(blank=True)),
                ('read_num', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('comment_content', models.CharField(max_length=1000)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
    ]
